apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  namespace: mateapp
  labels:
    app: my-daemonset
spec:
  selector:
    matchLabels:
      app: my-daemonset
  template:
    metadata:
      labels:
        app: my-daemonset
    spec:
      containers:
      - name: my-daemonset
        image: busyboxplus:curl
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "150m"